<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, Photo Slideshow Website, Photo Slideshow Template" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#ffffff">
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="data1/images/1925204_723796124341876_5594382264071692551_n.jpg" alt="1925204_723796124341876_5594382264071692551_n" title="1925204_723796124341876_5594382264071692551_n" id="wows1_0"/></li>
<li><img src="data1/images/20150629145639.jpg" alt="20150629145639" title="20150629145639" id="wows1_1"/></li>
<li><img src="data1/images/20150629145654.jpg" alt="20150629145654" title="20150629145654" id="wows1_2"/></li>
<li><img src="data1/images/20150629145726.jpg" alt="20150629145726" title="20150629145726" id="wows1_3"/></li>
<li><img src="data1/images/fb_img_1435567602197.jpg" alt="FB_IMG_1435567602197" title="FB_IMG_1435567602197" id="wows1_4"/></li>
<li><img src="data1/images/fb_img_1435567690465.jpg" alt="FB_IMG_1435567690465" title="FB_IMG_1435567690465" id="wows1_5"/></li>
<li><img src="data1/images/fb_img_1435568012767.jpg" alt="FB_IMG_1435568012767" title="FB_IMG_1435568012767" id="wows1_6"/></li>
<li><img src="data1/images/img_301705055624773.jpg" alt="IMG_301705055624773" title="IMG_301705055624773" id="wows1_7"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="1925204_723796124341876_5594382264071692551_n"><img src="data1/tooltips/1925204_723796124341876_5594382264071692551_n.jpg" alt="1925204_723796124341876_5594382264071692551_n"/>1</a>
<a href="#" title="20150629145639"><img src="data1/tooltips/20150629145639.jpg" alt="20150629145639"/>2</a>
<a href="#" title="20150629145654"><img src="data1/tooltips/20150629145654.jpg" alt="20150629145654"/>3</a>
<a href="#" title="20150629145726"><img src="data1/tooltips/20150629145726.jpg" alt="20150629145726"/>4</a>
<a href="#" title="FB_IMG_1435567602197"><img src="data1/tooltips/fb_img_1435567602197.jpg" alt="FB_IMG_1435567602197"/>5</a>
<a href="#" title="FB_IMG_1435567690465"><img src="data1/tooltips/fb_img_1435567690465.jpg" alt="FB_IMG_1435567690465"/>6</a>
<a href="#" title="FB_IMG_1435568012767"><img src="data1/tooltips/fb_img_1435568012767.jpg" alt="FB_IMG_1435568012767"/>7</a>
<a href="#" title="IMG_301705055624773"><img src="data1/tooltips/img_301705055624773.jpg" alt="IMG_301705055624773"/>8</a>
</div></div>
<a class="wsl" href="http://wowslider.com">Free Photo Slideshow For Website by WOWSlider.com v2.4</a>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>